import{useEffect,useRef,useState}from'react';
type Message={role:'user'|'assistant';text:string};type InstallEvent=Event&{prompt:()=>Promise<{outcome:string}>};
const starter:Message[]=[{role:'assistant',text:'Hey. I’m NETO. Talk to me or type a message.'}];
export default function App(){
const[messages,setMessages]=useState(starter),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[listening,setListening]=useState(false),[settings,setSettings]=useState(false),[installReady,setInstallReady]=useState(false),[installed,setInstalled]=useState(false),[muted,setMuted]=useState(false);const installRef=useRef<InstallEvent|null>(null),recognitionRef=useRef<any>(null);
useEffect(()=>{setInstalled(window.matchMedia('(display-mode: standalone)').matches||(window.navigator as any).standalone===true);const a=(e:Event)=>{e.preventDefault();installRef.current=e as InstallEvent;setInstallReady(true)},b=()=>{installRef.current=null;setInstallReady(false);setInstalled(true)};window.addEventListener('beforeinstallprompt',a);window.addEventListener('appinstalled',b);return()=>{window.removeEventListener('beforeinstallprompt',a);window.removeEventListener('appinstalled',b)}},[]);
const speak=(text:string)=>{if(muted||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text))};
const send=async(raw?:string)=>{const text=(raw??input).trim();if(!text||busy)return;setInput('');setMessages(p=>[...p,{role:'user',text}]);setBusy(true);try{const history=[...messages,{role:'user',text}],r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history})}),d=await r.json();if(!r.ok)throw Error(d?.error||'Request failed');const answer=String(d.text||'I didn’t receive a response.');setMessages(p=>[...p,{role:'assistant',text:answer}]);speak(answer)}catch(e){setMessages(p=>[...p,{role:'assistant',text:`I hit a problem: ${e instanceof Error?e.message:'Something went wrong.'}`}])}finally{setBusy(false)}};
const startListening=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setMessages(p=>[...p,{role:'assistant',text:'Voice input is not supported by this browser. You can still type to me.'}]);return}if(listening){recognitionRef.current?.stop();return}const r=new SR();r.lang=navigator.language||'en-US';r.interimResults=true;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript;if(t.trim())send(t.trim())};recognitionRef.current=r;r.start()};
const install=async()=>{if(!installRef.current)return;const p=installRef.current;installRef.current=null;setInstallReady(false);await p.prompt()};
return <main className="app"><header className="topbar"><div className="brand"><span className="brand-dot"/>NETO</div><button className="icon-btn" onClick={()=>setSettings(true)}>⚙</button></header>
<section className="orb-area"><div className={`orb ${busy?'busy':''} ${listening?'listening':''}`}><div className="orb-core"/><div className="orb-ring ring-one"/><div className="orb-ring ring-two"/></div><div className="status">{busy?'Thinking…':listening?'Listening…':'Ready'}</div></section>
<section className="conversation" aria-live="polite">{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}><div className="role">{m.role==='user'?'You':'NETO'}</div><div>{m.text}</div></div>)}</section>
<section className="composer"><div className="input-row"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Type a message…" rows={1} disabled={busy}/><button className={`voice-btn ${listening?'active':''}`} onClick={startListening}>{listening?'■':'🎙'}</button><button className="send-btn" onClick={()=>send()} disabled={!input.trim()||busy}>➤</button></div><div className="composer-note">Enter to send · Shift+Enter for a new line</div></section>
{installReady&&!installed&&<div className="install-card"><div><strong>Install NETO</strong><span>Keep NETO on your home screen and open it like an app.</span></div><button onClick={install}>Install app</button></div>}
{settings&&<div className="settings-backdrop" onClick={()=>setSettings(false)}><aside className="settings-panel" onClick={e=>e.stopPropagation()}><div className="settings-hero"><button className="home-btn" onClick={()=>setSettings(false)}>⌂ Home</button><button className="close-btn" onClick={()=>setSettings(false)}>×</button><div className="settings-orb"/><h2>NETO Settings</h2><p>Shape how your companion behaves.</p></div><div className="settings-grid"><button className="setting-card" onClick={()=>setMuted(v=>!v)}><span className="card-icon">🔊</span><span><b>Voice replies</b><small>{muted?'Muted':'Enabled'}</small></span><em>{muted?'OFF':'ON'}</em></button><button className="setting-card" onClick={install} disabled={!installReady}><span className="card-icon">⌁</span><span><b>Install app</b><small>{installed?'Already installed':installReady?'Ready to install':'Browser controls availability'}</small></span><em>OPEN</em></button><div className="setting-card info"><span className="card-icon">✦</span><span><b>Voice input</b><small>Uses your browser’s speech recognition when available.</small></span></div></div></aside></div>}</main> }